services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      AMPLITUDE_API_KEY: ${AMPLITUDE_API_KEY}
      AMPLITUDE_SECRET_KEY: ${AMPLITUDE_SECRET_KEY}
      AMPLITUDE_ACCOUNT_PROP: ${AMPLITUDE_ACCOUNT_PROP}
      AUTH_PASSWORD: ${AUTH_PASSWORD}
      AUTH_SECRET: ${AUTH_SECRET}
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      CH_HOST: ${CH_HOST}
      CH_USER: ${CH_USER}
      CH_PASS: ${CH_PASS}
      CB_SITE: ${CB_SITE}
      CB_KEY: ${CB_KEY}
      ZOHO_DESK_ORG_ID: ${ZOHO_DESK_ORG_ID}
      ZOHO_CLIENT_ID: ${ZOHO_CLIENT_ID}
      ZOHO_CLIENT_SECRET: ${ZOHO_CLIENT_SECRET}
      ZOHO_REFRESH_TOKEN: ${ZOHO_REFRESH_TOKEN}
    restart: unless-stopped
